# Scan using:
#   $ nix run nixpkgs#gitleaks -- git -v

[[rules]]
id = "nix-secrets"
# Match any single-line quoted string of reasonable characters.
regex = '''(?m)['"]([^'"\s\n]+)['"]'''
# All the secret keys I use are actually strong secrets, so have high entropy.
entropy = 4.5

# Allowlist here means "allow there to be secrets", i.e. ignore.
[allowlist]
paths = [
  '.*flake\.lock$'
]
